Repository Survival-From-Epidemic/Survival-From-Epidemic-Backend, pull requests merged in 2023-10, with the labels that each got.

#3 Merge: (#1)Exception 처리
  src/main/kotlin/team/sfe/server/global/.gitkeep
  src/main/kotlin/team/sfe/server/global/error/CustomException.kt
  src/main/kotlin/team/sfe/server/global/error/ErrorResponse.kt
  src/main/kotlin/team/sfe/server/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/team/sfe/server/global/exception/GlobalExceptions.kt
  src/main/kotlin/team/sfe/server/global/filter/FilterConfig.kt
  src/main/kotlin/team/sfe/server/global/filter/GlobalExceptionFilter.kt
Labels: setting

#5 Merge: (#4)Ktlint 적용
  .editorconfig
  .github/workflows/ktlint-check.yml
  build.gradle.kts
  src/main/kotlin/team/sfe/server/global/error/CustomException.kt
  src/main/kotlin/team/sfe/server/global/error/ErrorResponse.kt
  src/main/kotlin/team/sfe/server/global/filter/FilterConfig.kt
  src/test/kotlin/team/sfe/server/SurvivalFromEpidemicBackendApplicationTests.kt
Labels: setting

#8 Merge: (#6)CI 세팅
  .editorconfig
  .github/workflows/ci.yml
  .github/workflows/ktlint-check.yml
  .github/workflows/lint.yml
  src/main/kotlin/team/sfe/server/global/error/CustomException.kt
  src/main/kotlin/team/sfe/server/global/error/ErrorResponse.kt
  src/main/kotlin/team/sfe/server/global/filter/FilterConfig.kt
  src/main/kotlin/team/sfe/server/global/filter/GlobalExceptionFilter.kt
  src/test/kotlin/team/sfe/server/SurvivalFromEpidemicBackendApplicationTests.kt
Labels: setting

#9 Merge: Security 세팅
  src/main/kotlin/team/sfe/server/global/security/SecurityConfig.kt
Labels: setting

#11 Merge: (#10)REST Docs 세팅
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .gitignore
  build.gradle.kts
  src/main/kotlin/team/sfe/server/domain/.gitkeep
  src/main/kotlin/team/sfe/server/domain/HealthCheckController.kt
  src/main/resources/application.yml
  src/test/kotlin/team/sfe/server/SfeApiControllerDocTest.kt
Labels: setting

#13 Merge: (#12) JWT 세팅
  build.gradle.kts
  src/main/kotlin/team/sfe/server/domain/user/domain/type/Authority.kt
  src/main/kotlin/team/sfe/server/global/security/exception/SecurityExceptions.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/ConfigurationPropertiesConfig.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtConstant.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtParser.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtProperties.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtProvider.kt
  src/main/resources/application.yml
Labels: setting

#15 Merge: (#14)남은 시큐리티 설정
  src/main/kotlin/team/sfe/server/global/config/ConfigurationPropertiesConfig.kt
  src/main/kotlin/team/sfe/server/global/filter/FilterConfig.kt
  src/main/kotlin/team/sfe/server/global/filter/JwtFilter.kt
  src/main/kotlin/team/sfe/server/global/security/SecurityConfig.kt
  src/main/kotlin/team/sfe/server/global/security/auth/AuthDetails.kt
  src/main/kotlin/team/sfe/server/global/security/auth/AuthDetailsService.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtParser.kt
Labels: feat

#21 Merge: (#20) Github Action MySQL 설정
  .github/workflows/ci.yml
Labels: bug

#24 Merge: (#22) jwt 테스트 코드 작성
  .github/workflows/ci.yml
  build.gradle.kts
  src/main/kotlin/team/sfe/server/domain/user/domain/User.kt
  src/main/kotlin/team/sfe/server/domain/user/domain/repository/UserRepository.kt
  src/main/kotlin/team/sfe/server/domain/user/exception/UserExceptions.kt
  src/main/kotlin/team/sfe/server/global/filter/JwtFilter.kt
  src/main/kotlin/team/sfe/server/global/security/auth/AuthDetailsService.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtParser.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtProperties.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtProvider.kt
  src/test/kotlin/team/sfe/server/global/security/jwt/JwtProviderTest.kt
  src/test/resources/application.yml
Labels: test

#28 Merge: (#27) ci application.yml 생성
  .github/workflows/ci.yml
  .gitignore
  build.gradle.kts
Labels: bug

#26 Merge: refresh token 적용
  src/main/kotlin/team/sfe/server/domain/refreshToken/domain/RefreshToken.kt
  src/main/kotlin/team/sfe/server/domain/refreshToken/domain/repository/RefreshTokenRepository.kt
  src/main/kotlin/team/sfe/server/global/redis/RedisConfig.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtProperties.kt
  src/main/kotlin/team/sfe/server/global/security/jwt/JwtProvider.kt
  src/main/resources/application.yml
Labels: feat
